spring:
  application.name:
    tgmeng-api


server:
  port: 4399
  servlet:
    context-path: /api

forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 3000        # 连接超时时间，单位为毫秒
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒
  log-enabled: true            # 打开或关闭日志（默认为 true）
  log-request: true            # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
  auto-redirection: true # true 为开启，false 为关闭 # 全局自动重定向开关，默认为开启
  max-retry-count: 3           # 请求失败后重试次数（默认为 0 次不重试）